version: '3'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'

  api:
    build:
      context: ./api
      args:
        - NODE_ENV=development
    env_file:
      - ./api/.env
    ports:
      - 1800:1800
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  gulp:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    build:
      context: ./website-gulp
      args:
        - NODE_ENV=development
    env_file:
      - ./website-gulp/.env
    ports:
      - 9988:9988
    volumes:
      - ./website-gulp:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - api

  webpack:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./website-webpack
      args:
        - NODE_ENV=development
    env_file:
      - ./website-webpack/.env
    ports:
      - 3000:3000
    volumes:
      - ./website-webpack:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - api
